# Generated by Django 5.0.1 on 2024-01-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('business', models.CharField(max_length=255)),
                ('employees', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('additional', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('your_email', models.EmailField(max_length=254)),
                ('accept_terms', models.BooleanField(default=False)),
            ],
        ),
    ]
